### ISSUE TITLE
zspotify docker tag 2.0.3 PremiumAccountRequired error

### ISSUE THREAD

**Issue by digitalsushi** [jsavargas/zspotify#107]
Using the docker container tagged as 2.0.3

```
docker run -v ${HOME}/.zspotify:/root/.zspotify -v ${HOME}/Music:/root/Music -it jsavargas/zspotify -v
ZSpotify 2.0.3
```

When I run the container (or also pass the -f flag for 'force premium') I always receive

```
docker run -v ${HOME}/.zspotify:/root/.zspotify -v ${HOME}/Music:/root/Music -it jsavargas/zspotify
Traceback (most recent call last):
  File "/usr/local/bin/zspotify", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/zspotify/__main__.py", line 934, in main
    zs.start()
  File "/usr/local/lib/python3.9/site-packages/zspotify/__main__.py", line 859, in start
    while not self.login():
  File "/usr/local/lib/python3.9/site-packages/zspotify/__main__.py", line 317, in login
    return self.zs_api.login(username, password)
  File "/usr/local/lib/python3.9/site-packages/zspotify/zspotify_api.py", line 78, in login
    Session.Builder().user_pass(
  File "/usr/local/lib/python3.9/site-packages/librespot/core.py", line 1287, in create
    session.authenticate(self.login_credentials)
  File "/usr/local/lib/python3.9/site-packages/librespot/core.py", line 709, in authenticate
    self.__authenticate_partial(credential, False)
  File "/usr/local/lib/python3.9/site-packages/librespot/core.py", line 1067, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: PremiumAccountRequired
```

Using https://api.spotify.com/v1/me to interrogate my account I indeed have a premium:

```
{
  "country": "US",
  "display_name": "redacted",
  "email": "redacted",
  "explicit_content": {
    "filter_enabled": false,
    "filter_locked": false
  },
  "external_urls": {
    "spotify": "https://open.spotify.com/user/redacted"
  },
  "followers": {
    "href": null,
    "total": 1
  },
  "href": "https://api.spotify.com/v1/users/redacted",
  "id": "redacted",
  "images": [],
  "product": "premium",
  "type": "user",
  "uri": "spotify:user:redacted"
}
```

Thank you

**Comment by digitalsushi** [comment]
Ah, I've seen https://github.com/kokarare1212/librespot-python/issues/193 just a moment later. So this is redundant.
