### ISSUE TITLE
Getting a MemoryError 

### ISSUE THREAD

**Issue by KarlRW** [jsavargas/zspotify#119]
It seems I am able to download/convert files but when it comes to saving the file to the disk I am running into an error.

**OS**: Windows 10
**Python**: 32bit python 3.11
FFMPEG is in my windows path (had issue with this originally)
**Side note**: I commented out: `import music_tag` because I wasn't sure how to import it and it seems the code has a way to handle not having that module.

Error:
```
 File "C:\Program Files (x86)\Python311_32\Lib\subprocess.py", line 1552, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
MemoryError
```

Full command / output:
```

(env) PS A:\.code\py\standalone\2023\32bit\7-2023> python  .\zpotify\ -ep 7musTKoozIzhs59688mZg8


    ███████ ███████ ██████   ██████  ████████ ██ ███████ ██    ██
       ███  ██      ██   ██ ██    ██    ██    ██ ██       ██  ██
      ███   ███████ ██████  ██    ██    ██    ██ █████     ████
     ███         ██ ██      ██    ██    ██    ██ ██         ██
    ███████ ███████ ██       ██████     ██    ██ ██         ██


version: unknown
[ DETECTED FREE ACCOUNT - USING HIGH QUALITY ]

Downloading #1216 - Sir Roger Penrose episode
Using OGG_VORBIS_96 because preferred AudioQuality.HIGH couldn't be found.
The Joe Rogan Experience - #1216 - Sir Roger Penrose.mp3: 100%|███████████████████| 55.7M/55.7M [00:15<00:00, 3.87MB/s]
Converting #1216 - Sir Roger Penrose episode
Exception in thread Thread-6 (_readerthread):
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python311_32\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Python311_32\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files (x86)\Python311_32\Lib\subprocess.py", line 1552, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
MemoryError
```

**Comment by KarlRW** [comment]
Tried running in 64 bit version of python 3.10 as admin and it worked.

**Comment by niclimcy** [comment]
eh i guess this requires a fix, file is saved to a variable which takes up a significant amount of memory
