### ISSUE TITLE
Files reencoded even when .ogg format is used

### ISSUE THREAD

**Issue by bladeSk** [jsavargas/zspotify#127]
Zspotify had an option to save the original stream. When downloading podcasts, the current version converts the original 96kbps file to a new 160kbps file. This not only increases the file size, but also degrades the quality by reencoding a lossy ogg file into another lossy ogg file. I would expect that using `-af ogg` would keep the stream as-is.

Commit 86c5bc0, using a free Spotify account.

**Comment by Laiteux** [comment]
Note that setting audio tags won't work, apparently:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python311\Scripts\zspotify.exe\__main__.py", line 7, in <module>
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python311\Lib\site-packages\zspotify\__main__.py", line 964, in main    zs.start()
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python311\Lib\site-packages\zspotify\__main__.py", line 921, in start
    self.download_by_url(track)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python311\Lib\site-packages\zspotify\__main__.py", line 708, in download_by_url
    ret = self.download_track(parsed_url['track'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python311\Lib\site-packages\zspotify\__main__.py", line 563, in download_track
    self.set_audio_tags(fullpath,
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python311\Lib\site-packages\zspotify\__main__.py", line 398, in set_audio_tags
    tags = music_tag.load_file(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python311\Lib\site-packages\music_tag\__init__.py", line 66, in load_file
    raise NotImplementedError("Mutagen type {0} not implemented"
NotImplementedError: Mutagen type <class 'NoneType'> not implemented
```

**Comment by niclimcy** [comment]
I have no idea how to use save stream data as is, the vorbis file looks malformed when I try to save it to a file directly

**Comment by bladeSk** [comment]
I tried downloading a song and a podcast using my [hacky modified version of Zspotify](https://github.com/jsavargas/zspotify/files/12764711/ogg.patch) and the resulting files seemed perfectly valid, as far as I can tell. FFMPEG, Audacity, Foobar2000, MPC-HC and Android played them just fine.

Can you test if this produces an invalid stream?

**Comment by niclimcy** [comment]
Please try https://github.com/jsavargas/zspotify/pull/143

**Comment by bladeSk** [comment]
Excellent! It works. However, there's an issue when adding tags to the file - [stack trace.txt](https://github.com/jsavargas/zspotify/files/12777521/stack.trace.txt). Oddly enough, the file seems to get tagged properly, complete with cover art. The same thing happens in my hacky version.

**Comment by niclimcy** [comment]
> Excellent! It works. However, there's an issue when adding tags to the file - [stack trace.txt](https://github.com/jsavargas/zspotify/files/12777521/stack.trace.txt). Oddly enough, the file seems to get tagged properly, complete with cover art. The same thing happens in my hacky version.

Seems to be related to https://github.com/jsavargas/zspotify/issues/137

I will merge the downloader commits first in that case
