### ISSUE TITLE
how i fix this?

### ISSUE THREAD

**Issue by Bob4716** [jsavargas/zspotify#130]
Error: C:\Users\xxx>C:\Users\xx\AppData\Roaming\Python\Python311\Scripts\zspotify -al ALBUM, --album ALBUM https://open.spotify.com/album/2NNTwDg6TiMRM4pzTslnGQ?si=_pO14NdjSyqSHBD7WG0Vtw
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xx\AppData\Roaming\Python\Python311\Scripts\zspotify.exe\__main__.py", line 4, in <module>
  File "C:\Users\xxxj\AppData\Roaming\Python\Python311\site-packages\zspotify\__main__.py", line 2, in <module>
    from .zspotify_api import ZSpotifyApi
  File "C:\Users\xxx\AppData\Roaming\Python\Python311\site-packages\zspotify\zspotify_api.py", line 2, in <module>
    from librespot.audio.decoders import AudioQuality, VorbisOnlyAudioQuality
  File "C:\Users\xxj\AppData\Roaming\Python\Python311\site-packages\librespot\__init__.py", line 3, in <module>
    from librespot.proto.Keyexchange_pb2 import BuildInfo, Platform, Product, ProductFlags
  File "C:\Users\xxx\AppData\Roaming\Python\Python311\site-packages\librespot\proto\Keyexchange_pb2.py", line 31, in <module>
    _descriptor.EnumValueDescriptor(
  File "C:\Users\xxxj\AppData\Roaming\Python\Python311\site-packages\google\protobuf\descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

whats wrong? how i fix this?

**Comment by Soltinator** [comment]
Try different python versions and see how that goes
Oh BTW. Try and install using pip.
