### ISSUE TITLE
librespot error

### ISSUE THREAD

**Issue by renchris** [jsavargas/zspotify#144]
I get this error if I try to do any function with ZSpotify

I am on ZSpotify 2.0.4 and Python 3.11.4

Let me know what other details are needed to help debug

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/zspotify", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/zspotify/__main__.py", line 950, in main
    zs.start()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/zspotify/__main__.py", line 875, in start
    while not self.login():
              ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/zspotify/__main__.py", line 316, in login
    return self.zs_api.login(username, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/zspotify/zspotify_api.py", line 71, in login
    self.init_token()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/zspotify/zspotify_api.py", line 60, in init_token
    self.session = Session.Builder().stored_file(stored_credentials=str(self.credentials)).create()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/librespot/core.py", line 1317, in create
    session.authenticate(self.login_credentials)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/librespot/core.py", line 711, in authenticate
    self.__authenticate_partial(credential, False)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/librespot/core.py", line 1077, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: TravelRestriction
```

**Comment by niclimcy** [comment]
Update to 2.1.0, 2.0.4 isn’t the latest version anymore

**Comment by alan-null** [comment]
I am still able to reproduce it:
- python 3.11.4
- zspotify 2.1.0

**Comment by alan-null** [comment]
@renchris 
I found a reason. Please notice this part: `SpotifyAuthenticationException: TravelRestriction`

```
Can't log in abroad
You can use a free Spotify account in a different country or region for up to 14 days.
```

You have to open your spotify account and set new country/region
https://support.spotify.com/us/article/cant-log-in-abroad/

Then you will be able to use **zspotify**.

**Comment by renchris** [comment]
I am using a newly created account with a Premium trial. I set up the Premium payment information to be in my current region as well.

<img width="821" alt="image" src="https://github.com/jsavargas/zspotify/assets/57972348/ba612a7d-aa15-4bfc-8a2a-54e57a89f847">

**Comment by alan-null** [comment]
@renchris No idea then, I am using FREE account
