### ISSUE TITLE
cannot send credentials.

### ISSUE THREAD

**Issue by div4r4k** [jsavargas/zspotify#146]
Hello, when I try to get some episode:

zspotify -ep https://open.spotify.com/episode/4W6GofFvCzIR0vSwVRyTml?si=7c7db4cb5ad8465a -f

Returns:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "d:\Users\zzz\AppData\Roaming\Python\Python311\Scripts\zspotify.exe\__main__.py", line 7, in <module>
  File "d:\Users\zzz\AppData\Roaming\Python\Python311\site-packages\zspotify\__main__.py", line 697, in main
    zs.start()
  File "d:\Users\zzz\AppData\Roaming\Python\Python311\site-packages\zspotify\__main__.py", line 614, in start
    while not self.login():
              ^^^^^^^^^^^^
  File "d:\Users\zzz\AppData\Roaming\Python\Python311\site-packages\zspotify\__main__.py", line 243, in login
    if self.respot.is_authenticated(username, password):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\zzz\AppData\Roaming\Python\Python311\site-packages\zspotify\respot.py", line 28, in is_authenticated
    if self.auth.login(username, password):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\zzz\AppData\Roaming\Python\Python311\site-packages\zspotify\respot.py", line 86, in login
    return self._authenticate_with_user_pass(username, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\zzz\AppData\Roaming\Python\Python311\site-packages\zspotify\respot.py", line 111, in _authenticate_with_user_pass
    self._persist_credentials_file()
  File "d:\Users\zzz\AppData\Roaming\Python\Python311\site-packages\zspotify\respot.py", line 92, in _persist_credentials_file
    Path("credentials.json").rename(self.credentials)
  File "C:\Program Files\Python311\Lib\pathlib.py", line 1175, in rename
    os.rename(self, target)
OSError: [WinError 17] El sistema no puede mover el archivo a otra unidad de disco: 'credentials.json' -> 'd:\\Users\\zzz\\.zspotify\\credentials.json'

**Comment by niclimcy** [comment]
Weird, pathlib does not like your custom drive setup

**Comment by div4r4k** [comment]
Yes... I have a custom drive setup.. System on a drive and user folder in
another.

**Comment by div4r4k** [comment]
I tried to run the program from c drive and seems to bypass this issue.... 

Now when I try to download a podcast, I get this:

zspotify -ep https://open.spotify.com/episode/4Tzm1M0ucC5Ncj2NSb7yt8?si=6fb0fffdc8a349d4

###   get_track_info - FAILED TO QUERY METADATA   ###
track_id: 4Tzm1M0ucC5Ncj2NSb7yt8
'NoneType' object is not subscriptable
Skipping 4Tzm1M0ucC5Ncj2NSb7yt8 - Could not get track info
