### ISSUE TITLE
Downloading in ogg format fails

### ISSUE THREAD

**Issue by watn3y** [jsavargas/zspotify#161]
**Environment:**
 - OS: `Docker 24.0.7 on Debian 12`
 - Python version: `3.11.6`
 - Launch command: 
``` 
 docker run -v ~/.zspotify:/root/.zspotify -it jsavargas/zspotify:latest -af ogg https://open.spotify.com/track/4PTG3Z6ehGkBFwjybzWkR8?si=f4f7de2101fc4596
``` 

**Describe the bug**
When downloading a file with `-af ogg` it fails to download. 

**To Reproduce**
1.  Download any file in ogg format
2. Profit

**Stack Trace**

``` 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/mutagen/ogg.py", line 90, in __init__
    crc, segments) = struct.unpack("<4sBBqIIiB", header)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 27 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/mutagen/ogg.py", line 589, in save
    self.tags._inject(filething.fileobj, padding)
  File "/usr/local/lib/python3.11/site-packages/mutagen/oggvorbis.py", line 146, in _inject
    OggPage.replace(fileobj, old_pages, new_pages)
  File "/usr/local/lib/python3.11/site-packages/mutagen/ogg.py", line 438, in replace
    cls.renumber(fileobj, serial, sequence)
  File "/usr/local/lib/python3.11/site-packages/mutagen/ogg.py", line 230, in renumber
    page = OggPage(fileobj)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mutagen/ogg.py", line 92, in __init__
    raise error("unable to read full header; got %r" % header)
mutagen.ogg.error: unable to read full header; got b'\x00\x00\x00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/zspotify", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zspotify/__main__.py", line 697, in main
    zs.start()
  File "/usr/local/lib/python3.11/site-packages/zspotify/__main__.py", line 672, in start
    self.download_by_url(query)
  File "/usr/local/lib/python3.11/site-packages/zspotify/__main__.py", line 504, in download_by_url
    ret = self.download_track(parsed_url["track"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zspotify/__main__.py", line 348, in download_track
    self.tagger.set_audio_tags(
  File "/usr/local/lib/python3.11/site-packages/zspotify/tagger.py", line 22, in set_audio_tags
    self._set_other_tags(fullpath, artists, name, album_name, release_year, disc_number,
  File "/usr/local/lib/python3.11/site-packages/zspotify/tagger.py", line 75, in _set_other_tags
    tags.save()
  File "/usr/local/lib/python3.11/site-packages/music_tag/file.py", line 374, in save
    self.mfile.save(**kwargs)
  File "/usr/local/lib/python3.11/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mutagen/ogg.py", line 591, in save
    reraise(self._Error, e, sys.exc_info()[2])
  File "/usr/local/lib/python3.11/site-packages/mutagen/_util.py", line 43, in reraise
    raise tp(value).with_traceback(tb)
  File "/usr/local/lib/python3.11/site-packages/mutagen/ogg.py", line 589, in save
    self.tags._inject(filething.fileobj, padding)
  File "/usr/local/lib/python3.11/site-packages/mutagen/oggvorbis.py", line 146, in _inject
    OggPage.replace(fileobj, old_pages, new_pages)
  File "/usr/local/lib/python3.11/site-packages/mutagen/ogg.py", line 438, in replace
    cls.renumber(fileobj, serial, sequence)
  File "/usr/local/lib/python3.11/site-packages/mutagen/ogg.py", line 230, in renumber
    page = OggPage(fileobj)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mutagen/ogg.py", line 92, in __init__
    raise error("unable to read full header; got %r" % header)
mutagen.oggvorbis.OggVorbisHeaderError: unable to read full header; got b'\x00\x00\x00'
```

**Comment by niclimcy** [comment]
Can reproduce but not sure how to solve

**Comment by RicheeNektar** [comment]
The error also occurs for source, but you can listen to both files...

**Comment by scandolio** [comment]
This issue happens when writing OGG tags. Don't know where it fails, but a quick fix would be to comment lines 21 to 23 in tagger.py (call to _set_other_tags function). 
I use ncmpcpp with its own tag editor, so I do the job manually after that... Only missing data is the album art.

**Comment by themitzman** [comment]
I had this issue but instead of commenting it out so it never tags, I just wrapped that line in a try/except block and it works great. This gets around the error and better error handling could be done later.

```
else:
            try:
                self._set_other_tags(fullpath, artists, name, album_name, release_year, disc_number, track_number, track_id_str, image_url)
            except:
                print("couldn't set tags")

```

**Comment by tarial** [comment]
Not sure if this helps, but the error does not occur on every track and when it does, the tags including album art are set.

``` bash
$ python -m zspotify --archive /dev/null -af source https://open.spotify.com/playlist/37i9dQZF1DX4WYpdgoIcn6
Error loading archive: Expecting value: line 1 column 1 (char 0)


    ███████ ███████ ██████   ██████  ████████ ██ ███████ ██    ██
       ███  ██      ██   ██ ██    ██    ██    ██ ██       ██  ██
      ███   ███████ ██████  ██    ██    ██    ██ █████     ████
     ███         ██ ██      ██    ██    ██    ██ ██         ██
    ███████ ███████ ██       ██████     ██    ██ ██         ██


version: 2.1.0
[ DETECTED FREE ACCOUNT - USING HIGH QUALITY ]

Downloading Chill Hits playlist
100%|█████████████████████████████████████████████████████████████████████████████████████████████████▉| 3.13M/3.13M [00:00<00:00, 3.91MB/s]
Saving Arctic Monkeys - I Wanna Be Yours as source
Added to archive: Arctic Monkeys - I Wanna Be Yours
Setting audiotags Arctic Monkeys - I Wanna Be Yours
Finished downloading Arctic Monkeys - I Wanna Be Yours
100%|█████████████████████████████████████████████████████████████████████████████████████████████████▉| 3.82M/3.82M [00:00<00:00, 5.50MB/s]
Saving Tyla - Water as source
Added to archive: Tyla - Water
Setting audiotags Tyla - Water
Finished downloading Tyla - Water
100%|█████████████████████████████████████████████████████████████████████████████████████████████████▉| 3.74M/3.74M [00:00<00:00, 5.78MB/s]
Saving David Kushner - Daylight as source
Added to archive: David Kushner - Daylight
Setting audiotags David Kushner - Daylight
Traceback (most recent call last):
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/mutagen/ogg.py", line 90, in __init__
crc, segments) = struct.unpack("<4sBBqIIiB", header)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 27 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/mutagen/ogg.py", line 589, in save
self.tags._inject(filething.fileobj, padding)
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/mutagen/oggvorbis.py", line 146, in _inject
OggPage.replace(fileobj, old_pages, new_pages)
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/mutagen/ogg.py", line 438, in replace
cls.renumber(fileobj, serial, sequence)
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/mutagen/ogg.py", line 230, in renumber
page = OggPage(fileobj)
^^^^^^^^^^^^^^^^
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/mutagen/ogg.py", line 92, in __init__
raise error("unable to read full header; got %r" % header)
mutagen.ogg.error: unable to read full header; got b'\x00\x00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/zspotify/__main__.py", line 707, in <module>
main()
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/zspotify/__main__.py", line 700, in main
zs.start()
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/zspotify/__main__.py", line 675, in start
self.download_by_url(query)
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/zspotify/__main__.py", line 509, in download_by_url
ret = self.download_playlist(parsed_url["playlist"])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/zspotify/__main__.py", line 380, in download_playlist
self.download_track(song["id"], basepath, "playlist")
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/zspotify/__main__.py", line 351, in download_track
self.tagger.set_audio_tags(
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/zspotify/tagger.py", line 22, in set_audio_tags
self._set_other_tags(fullpath, artists, name, album_name, release_year, disc_number,
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/zspotify/tagger.py", line 75, in _set_other_tags
tags.save()
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/music_tag/file.py", line 374, in save
self.mfile.save(**kwargs)
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/mutagen/_util.py", line 156, in wrapper
return func(self, h, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/mutagen/ogg.py", line 591, in save
reraise(self._Error, e, sys.exc_info()[2])
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/mutagen/_util.py", line 43, in reraise
raise tp(value).with_traceback(tb)
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/mutagen/ogg.py", line 589, in save
self.tags._inject(filething.fileobj, padding)
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/mutagen/oggvorbis.py", line 146, in _inject
OggPage.replace(fileobj, old_pages, new_pages)
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/mutagen/ogg.py", line 438, in replace
cls.renumber(fileobj, serial, sequence)
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/mutagen/ogg.py", line 230, in renumber
page = OggPage(fileobj)
^^^^^^^^^^^^^^^^
File "/home/tarial/Store/Projects/zspotify-TEST/.venv/lib/python3.11/site-packages/mutagen/ogg.py", line 92, in __init__
raise error("unable to read full header; got %r" % header)
mutagen.oggvorbis.OggVorbisHeaderError: unable to read full header; got b'\x00\x00'
```

**Comment by WMP** [comment]
https://github.com/quodlibet/mutagen/issues/591

**Comment by EpicLPer** [comment]
I've written a bit of a workaround for this now which saves all Infos into a text file when it fails to write into the actual file.

**DISCLAIMER:** I'm very bad with Python (or any other programming language for that matter). This is probably written in a very awkward way, if you have any improvement comments please tell so :)

----

1. Open `tagger.py` located in `C:\Program Files\Python312\Lib\site-packages\zspotify\` (or wherever your Python install resides, for you it's probably in `appdata` somewhere).
2. Replace everything **ABOVE** the line `def _set_mp3_tags(self, fullpath, artist, name, album_name, release_year, disc_number, ` with the following:
```python
import music_tag
import requests
from mutagen import id3
from pathlib import Path

class AudioTagger:
    
    def __init__(self):
        pass

    def set_audio_tags(self, fullpath, artists=None, name=None, album_name=None, release_year=None,
                       disc_number=None, track_number=None, track_id_str=None, album_artist=None, image_url=None):
        """sets music_tag metadata using mutagen if possible"""
        
        album_artist = album_artist or artists  # Use artists if album_artist is None

        extension = str(fullpath).split('.')[-1]

        if extension == 'mp3':
            self._set_mp3_tags(fullpath, artists, name, album_name, release_year, disc_number, track_number, track_id_str, album_artist, image_url)
        else:
            try:
                self._set_other_tags(fullpath, artists, name, album_name, release_year, disc_number, track_number, track_id_str, image_url)
            except:
                print("ERROR: Unable to set tags on downloaded file, writing to text file instead...")
                fullpath_txt = fullpath.with_suffix(".txt")
                fallback_txt_file = open(fullpath_txt, "w")
                fallback_txt_file.write(
                    "Artist: " + str(artists) + "\n" +
                    "Name: " + str(name) + "\n" +
                    "Album: " + str(album_name) + "\n" +
                    "Release Year: " + str(release_year) + "\n" +
                    "Disc Number: " + str(disc_number) + "\n" +
                    "Track Number: " + str(track_number) + "\n" +
                    "Spotify URL: " + "https://open.spotify.com/track/" + track_id_str +
                    "Album Artist: " + str(album_artist) + "\n" +
                    "Image URL: " + str(image_url) + "\n")
                fallback_txt_file.close()
# Below this point the line should start with "def _set_mp3_tags(self, fullpath, artist, name, album_name, release_year, disc_number,"
```

---

The main thing I've added is `from pathlib import Path` at the very top and the `try:` `except:` section replacing the original line, thanks to @themitzman !

**Comment by themitzman** [comment]
@EpicLPer  you're very welcome. I'm not a python guy at all (first time writing with it but I am a coder).  I am in the process of modifying the entire project locally to work for my very specific cases (including writing out m3u playlists to mimic the order of my Spotify playlists as well as import them to Plex). I'm happy to share when I eventually finish.

**Comment by EpicLPer** [comment]
One thing I noticed with my script, it fails to properly open/write to files with special characters (such as Chinese symbols). Not sure how to fix this tho, for most tracks it works fine as of now.

**Comment by Leon-075** [comment]
I'm not sure why but when downloading a playlist, the first song is downloaded without issues (and with metadata), the next song mostly fails but sometimes works. Invoking zspotify with -s will download the last failed song with no issues and fail the next one again.

From the issue mentioned above:

> It always throws at the last Ogg page, trying to interpret the last couple null bytes as a header.
> The file still gets saved and once ran, the same ogg file will no longer cause the issue.
>
> However, the offsets also wildly change. On the file that errored previously the last two segments are now
> Header at offset 27

I'm not too familiar with mutagen, but could it explain why the song is correctly downloaded after the second try?

**Comment by EpicLPer** [comment]
From a quick uneducated guess this might seem as if parts of the OGG file from the previous download somehow get carried over to a new one destroying the header and/or adding a header to the previously downloaded file to the very end where there shouldn't be one anymore? Dirty caches maybe?
Really not sure... I have basically 0 idea if this could even be the case...
