### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by D3V1L0M3N** [jsavargas/zspotify#171]
**Environment:**
 - OS: Windows 10
 - Python version: 3.12.1
 - Launch command ``zspotify https://open.spotify.com/track/1wWMPiJmDfliMOBRj8ux5y?si=e187fcebd9904d49``

**Describe the bug**
This one song spits out a "Permission Error: Permission Denied" error in console and terminates the process immediately.

**To Reproduce**
1. Run ``zspotify https://open.spotify.com/track/1wWMPiJmDfliMOBRj8ux5y?si=e187fcebd9904d49``
2. ZSpotify downloads the song then produces an error
3. See below stack trace

**Stack Trace**
``` 
Search: https://open.spotify.com/track/1wWMPiJmDfliMOBRj8ux5y?si=ab783c7209a04c56
100%|████████████████████████████████████████████████████████████████████████████▉| 11.7M/11.7M [00:06<00:00, 1.89MB/s]
Converting Dana Winner - One Moment In Time to mp3
Added to archive: Dana Winner - One Moment In Time
Setting audiotags Dana Winner - One Moment In Time
Traceback (most recent call last):
  File "C:\Users\D3V1L0M3N\AppData\Local\Programs\Python\Python312\Lib\site-packages\mutagen\_util.py", line 251, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\D3V1L0M3N\\Music\\ZSpotify Music\\Dana Winner - One Moment In Time.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\D3V1L0M3N\AppData\Local\Programs\Python\Python312\Scripts\zspotify.exe\__main__.py", line 7, in <module>
  File "C:\Users\D3V1L0M3N\AppData\Local\Programs\Python\Python312\Lib\site-packages\zspotify\__main__.py", line 700, in main
    zs.start()
  File "C:\Users\D3V1L0M3N\AppData\Local\Programs\Python\Python312\Lib\site-packages\zspotify\__main__.py", line 690, in start
    self.search(self.args.search)
  File "C:\Users\D3V1L0M3N\AppData\Local\Programs\Python\Python312\Lib\site-packages\zspotify\__main__.py", line 539, in search
    self.download_by_url(query)
  File "C:\Users\D3V1L0M3N\AppData\Local\Programs\Python\Python312\Lib\site-packages\zspotify\__main__.py", line 507, in download_by_url
    ret = self.download_track(parsed_url["track"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D3V1L0M3N\AppData\Local\Programs\Python\Python312\Lib\site-packages\zspotify\__main__.py", line 351, in download_track
    self.tagger.set_audio_tags(
  File "C:\Users\D3V1L0M3N\AppData\Local\Programs\Python\Python312\Lib\site-packages\zspotify\tagger.py", line 19, in set_audio_tags
    self._set_mp3_tags(fullpath, artists, name, album_name, release_year, disc_number,
  File "C:\Users\D3V1L0M3N\AppData\Local\Programs\Python\Python312\Lib\site-packages\zspotify\tagger.py", line 50, in _set_mp3_tags
    tags.save()
  File "C:\Users\D3V1L0M3N\AppData\Local\Programs\Python\Python312\Lib\site-packages\mutagen\_util.py", line 185, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D3V1L0M3N\AppData\Local\Programs\Python\Python312\Lib\site-packages\mutagen\_util.py", line 154, in wrapper
    with _openfile(self, filething, filename, fileobj,
  File "C:\Users\D3V1L0M3N\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\D3V1L0M3N\AppData\Local\Programs\Python\Python312\Lib\site-packages\mutagen\_util.py", line 272, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 13] Permission denied: 'C:\\Users\\D3V1L0M3N\\Music\\ZSpotify Music\\Dana Winner - One Moment In Time.mp3'

C:\Users\D3V1L0M3N\Music\ZSpotify Music\CD Playlist #1>
```

**Comment by D3V1L0M3N** [comment]
Update: I suspect this issue was triggered by Windows Defender Real-time Protection doing whatever it does with new files, and blocking the file read/write stream while it does it's scans/heuristics.

After running the script again today, the song I previously had issues with downloaded fine but then errored on a new one. Temporarily disabling real-time protection succeeded all downloads error-free.
