### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by Screeper11** [jsavargas/zspotify#95]
Songs with long names crash and halt the program.

Error message:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/zspotify", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/zspotify/__main__.py", line 933, in main
    zs.start()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/zspotify/__main__.py", line 916, in start
    self.download_by_url(url)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/zspotify/__main__.py", line 684, in download_by_url
    ret = self.download_playlist(parsed_url['playlist'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/zspotify/__main__.py", line 561, in download_playlist
    self.download_track(song['id'], basepath, "playlist")
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/zspotify/__main__.py", line 507, in download_track
    if self.not_skip_existing and fullpath.exists():
                                  ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 1235, in exists
    self.stat()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 63] File name too long
```

**Comment by Screeper11** [comment]
**Example song to recreate the issue:**
https://open.spotify.com/track/3XAzZZoJeLmIGAGYH7rTBj

**Name of the song:**
_(637 characters)_
Feel Out Loud, 2Frères, Adria Kain, Alessia Cara, Ashley Sienna, Babygirl, Billy Raffoul, BLUE WILL, Boslen, Bryn, Crash Adams, Dominique Fils-Aimé, Donovan Woods, Fefe Dobson, Gracie Ella, GRAE, Haviah Mighty, Izzy-S, Jade LeMac, Jamie Fine, Jeanick Fournier, JESSIA, Johnny Orlando, JON VINYL, Jonathan Roy, JP Saxe, Jully Black, Katherine Li, Leela Gilday, Lilyisthatyou, LOKRE, LOONY, MacKenzie Porter, Marie-Mai, memyself&vi, NAYA ALI, Nicolina, Preston Pablo, Ralph, Rêve, Roy Woods, Ryland James, Sacha, Sarah McLachlan, Serena Ryder, Shawn Desman, Shawnee Kish, Stereos, Tafari Anthony, TALK - What I Wouldnt DoNorth Star Calling
