### ISSUE TITLE
Download for podcast fails

### ISSUE THREAD

**Issue by JanX2** [jsavargas/zspotify#99]
When I’m running zspotify with

`zspotify --episode 2knf2lQkB9Bwim2t2Nkahz`

it fails, probably somewhere in the API code that I don’t currently understand, with this output:

```
Downloading Brené with Dr. John Gottman and Dr. Julie Schwartz Gottman on The Love Prescription, Part 1 of 3 episode
Using OGG_VORBIS_96 because preferred AudioQuality.HIGH couldn't be found.
Unlocking Us with Brené Brown - Brené with Dr. John Gottman and Dr. Julie Schwartz Gottman on The Love Prescription, Part 1 of 3.mp3:  98%|███████████▊| 27.4M/27.9M [00:06<00:00, 3.98MB/s]###   download_track - FAILED TO DOWNLOAD   ###
Expecting value: line 1 column 1 (char 0)
2knf2lQkB9Bwim2t2Nkahz /Users/jan/Music/ZSpotify Podcast/Unlocking Us with Brené Brown - Brené with Dr. John Gottman and Dr. Julie Schwartz Gottman on The Love Prescription, Part 1 of 3.mp3
Unlocking Us with Brené Brown - Brené with Dr. John Gottman and Dr. Julie Schwartz Gottman on The Love Prescription, Part 1 of 3.mp3: 100%|████████████| 27.9M/27.9M [00:07<00:00, 4.07MB/s]
Converting Brené with Dr. John Gottman and Dr. Julie Schwartz Gottman on The Love Prescription, Part 1 of 3 episode
Added to archive: Unlocking Us with Brené Brown - Brené with Dr. John Gottman and Dr. Julie Schwartz Gottman on The Love Prescription, Part 1 of 3
Set audiotags Brené with Dr. John Gottman and Dr. Julie Schwartz Gottman on The Love Prescription, Part 1 of 3
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/mutagen/_util.py", line 250, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jan/Music/ZSpotify Podcast/Unlocking Us with Brené Brown - Brené with Dr. John Gottman and Dr. Julie Schwartz Gottman on The Love Prescription, Part 1 of 3.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/zspotify", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/zspotify/__main__.py", line 934, in main
    zs.start()
  File "/opt/homebrew/lib/python3.11/site-packages/zspotify/__main__.py", line 900, in start
    self.download_episode(episode)
  File "/opt/homebrew/lib/python3.11/site-packages/zspotify/__main__.py", line 761, in download_episode
    self.set_audio_tags(fullpath,
  File "/opt/homebrew/lib/python3.11/site-packages/zspotify/__main__.py", line 341, in set_audio_tags
    tags = id3.ID3(filename)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mutagen/id3/_file.py", line 76, in __init__
    super(ID3, self).__init__(*args, **kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/mutagen/id3/_tags.py", line 172, in __init__
    super(ID3Tags, self).__init__(*args, **kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/mutagen/_util.py", line 533, in __init__
    super(DictProxy, self).__init__(*args, **kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/mutagen/_tags.py", line 110, in __init__
    self.load(*args, **kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/mutagen/_util.py", line 184, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mutagen/_util.py", line 153, in wrapper
    with _openfile(self, filething, filename, fileobj,
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mutagen/_util.py", line 271, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: '/Users/jan/Music/ZSpotify Podcast/Unlocking Us with Brené Brown - Brené with Dr. John Gottman and Dr. Julie Schwartz Gottman on The Love Prescription, Part 1 of 3.mp3'
```

I think that the important hint is the `Expecting value: line 1 column 1 (char 0)`.

**Comment by niclimcy** [comment]
Did you install ffmpeg?

**Comment by JanX2** [comment]
Yes. I need it for other things and ffmpeg has been working flawlessly. :)

**Comment by DieterHolvoet** [comment]
I'm getting the exact same error. Related issues:
- https://github.com/jiaaro/pydub/issues/145
- https://github.com/jiaaro/pydub/issues/303
- https://github.com/jiaaro/pydub/issues/450
- https://github.com/jiaaro/pydub/issues/726

I was able to debug and fix the issue this way:
1. Follow the steps as described in https://github.com/jiaaro/pydub/issues/303#issuecomment-651848352. I had to run the following command: cat /path/to/your.mp3 | avprobe -of json -v info -show_format -show_streams
2. That command gave me this error: `dyld[79797]: Library not loaded: /opt/homebrew/opt/libvpx/lib/libvpx.7.dylib`, which I fixed by following the workaround as described here: https://www.reddit.com/r/ispyconnect/comments/12rjq0a/agentdvr_in_macos_m1/
3. After running the following command, zspotify was working again: `ln -s /opt/homebrew/opt/libvpx/lib/libvpx.8.dylib /opt/homebrew/opt/libvpx/lib/libvpx.7.dylib`

@jsavargas maybe it's worth documenting this as a common issue in the project README?
